### ISSUE TITLE
definitions of terms used 

### ISSUE THREAD

**Issue by tenkstepsaday** [andy6804tw/andy6804tw#1]
https://andy6804tw.github.io/taiwanreservoir/public/ is great. 
Thank you for providing this for the public to see.  
Could you provide an explanation on how each term is determined? 
For example, at Shigang Reservoir, 2021/6/7 at 12:00, "有效蓄水量：98.94萬立方公尺 今日進水量：1,898.10萬立方公尺". 
I've noticed that Shigang Res. had LOTs of water inflow in the last week, but its  有效蓄水量 actually went DOWN. 
I don't understand. 
Thanks.

**Comment by andy6804tw** [comment]
Dear @tenkstepsaday,
Thank you for your favorite. You can see [Open Data](https://fhy.wra.gov.tw/ReservoirPage_2011/StorageCapacity.aspx) provided by Water Resources Agency in Taiwan. In this data you can find that each reservoir have `進水量` and `出水量` everyday. Maybe I should show `出水量` in my web. To prevent people misunderstand it.

![](https://i.imgur.com/bp0ulEo.png)

If you have any questions or suggestions, please let me know. Thanks!

Best Regards,
yilin

**Comment by tenkstepsaday** [comment]
Hi, Yilin.
Thanks for your prompt reply.
"Maybe I should show 出水量 in my web."  --> this is a good idea.
YY
