### ISSUE TITLE
python-webcam-socket-streaming-multiple clients

### ISSUE THREAD

**Issue by brofessor9** [andy6804tw/andy6804tw#2]
Sir, I wish you have a good health. I am working on a project and I am stuck. I have a laptop(ubuntu 20.04LTS, built-in webcam), a amazon ec2 instance(ubuntu 20.04LTS). I want to stream livecam over network to multiple clients. I have already written script files 1 for laptop(webcam), 1 for amazon(cache-server) and 1 for clients. I run and success all script files over Wi-Fi. They are working. But, I can not achieve that how to operate this project over network. You said to me ' You can try ngrok' and I tried. I didn't understand which ip & port to write where. Can you declare for me?. I am adding
![amazon(cache server)](https://user-images.githubusercontent.com/21080252/122680878-32d85680-d1fa-11eb-9310-a5609a450909.jpg)
![client](https://user-images.githubusercontent.com/21080252/122680880-3370ed00-d1fa-11eb-9919-aff6786afca2.jpg)
![livecam-laptop](https://user-images.githubusercontent.com/21080252/122680883-34098380-d1fa-11eb-8cb2-7012544b60fb.jpg)
 all script files.

**Comment by andy6804tw** [comment]
Hi @brofessor9 , I'm good here! so you want to broadcast to multiple client who with different network?
I received your code from my email. Let me see.

**Comment by andy6804tw** [comment]
@brofessor9  I have read your code, and I think it’s too heavy to load under different networks. It will very lagging.
In your case I think you can try this [package](https://mux.com/) for better experience.

**Comment by brofessor9** [comment]
> @brofessor9 I have read your code, and I think it’s too heavy to load under different networks. It will very lagging.
> In your case I think you can try this [package](https://mux.com/) for better experience.

I will check it out. Thanks for replies. Have a nice & healty day!
